const XS = process.env.XS_DIR || require('path').join(require('os').tmpdir(), 'vq-verify', 'xscope');
const rows=require(require('path').join(XS, 'xscope-vibrato.json')).filter(r=>r.path===(process.argv[2]||'shared'));
const nn=a=>a.filter(x=>x!=null), mean=a=>{a=nn(a);return a.length?Math.round(a.reduce((s,x)=>s+x,0)/a.length):'—'}, rate=(a,f)=>{a=nn(a);return a.length?Math.round(100*a.filter(f).length/a.length):'—'}, k=(a,key)=>nn(a).map(x=>x[key]);
const M=[
['PM beg score (bands 85/60)',r=>mean(k(r.pitchMatch.beg,'now'))],
['PM int score',r=>mean(k(r.pitchMatch.int,'now'))],
['PM pro score',r=>mean(k(r.pitchMatch.pro,'now'))],
['PM int %≥75 (VocalLab reliable)',r=>rate(k(r.pitchMatch.int,'now'),x=>x>=75)],
['PM pro %≥75',r=>rate(k(r.pitchMatch.pro,'now'),x=>x>=75)],
['PM int %≥85 (good)',r=>rate(k(r.pitchMatch.int,'now'),x=>x>=85)],
['PM int score, 200ms MA',r=>mean(k(r.pitchMatch.int,'ma'))],
['PM pro score, 200ms MA',r=>mean(k(r.pitchMatch.pro,'ma'))],
['PM pro score, |median|',r=>mean(k(r.pitchMatch.pro,'med'))],
['Scale pro note (wk ≥80)',r=>mean(k(r.scaleNote.pro,'now'))],
['Scale pro %≥80',r=>rate(k(r.scaleNote.pro,'now'),x=>x>=80)],
['Scale int note',r=>mean(k(r.scaleNote.int,'now'))],
['Rift round',r=>mean(k(r.rift,'now'))],
['Boss pitch beg pass% (≥60)',r=>rate(k(r.boss['pitch/beginner'],'pass'),x=>x)],
['Boss pitch int pass% (≥70)',r=>rate(k(r.boss['pitch/intermediate'],'pass'),x=>x)],
['Boss pitch pro pass% (≥80)',r=>rate(k(r.boss['pitch/professional'],'pass'),x=>x)],
['Boss pitch score',r=>mean(k(r.boss['pitch/intermediate'],'acc'))],
['Boss sustain score',r=>mean(k(r.boss['sustain/intermediate'],'acc'))],
['Boss sustain int pass%',r=>rate(k(r.boss['sustain/intermediate'],'pass'),x=>x)],
['Boss agility int pass%',r=>rate(k(r.boss['agility/intermediate'],'pass'),x=>x)],
['Boss tremor score',r=>mean(k(r.boss['tremor/intermediate'],'acc'))],
['Boss tremor pro pass%',r=>rate(k(r.boss['tremor/professional'],'pass'),x=>x)],
['Karaoke note %≥70',r=>rate(r.karaoke,x=>x>=70)],
['Karaoke note score',r=>mean(r.karaoke)],
['Harmony note %≥75',r=>rate(r.harmony,x=>x>=75)],
['ChoirWorld held% (median±50)',r=>rate(nn(r.hm),x=>x.held)],
['Stay in Key % (±35)',r=>r.stayKey],
['Stay in Key %, 200ms MA',r=>r.stayKeyMA],
['OneTake pitch',r=>mean(k(r.oneTake,'pitch'))],
['OneTake stability',r=>mean(k(r.oneTake,'stab'))],
['RTF In tune % (±8)',r=>r.rtfInTune],
['RTF Steady %',r=>r.steadyPct],
['Tuner locked % (±6)',r=>r.tunerLocked],
['Tuner stability',r=>r.stabMean],
['Glider p95 px (gap ±35)',r=>r.gliderDy&&r.gliderDy.p95],
['voiced%',r=>r.voicedPct],
['real captureAccuracy x0.6',r=>r.xcheck?r.xcheck.join('/'):''],
];
console.log('metric'.padEnd(32)+rows.map(r=>r.case.padEnd(13)).join(''));
for(const [n,f] of M) console.log(n.padEnd(32)+rows.map(r=>String(f(r)).padEnd(13)).join(''));
